server:
  port: 8080

spring:
  application:
    name: "product-service"
  datasource:
    url: jdbc:mysql://localhost:3309/product_service
    username: product_service
    password: product_service
  jpa:
    hibernate:
      ddl-auto: none