server:
  port: 8080

spring:
  application:
    name: "product-service"
  datasource:
    url: jdbc:mysql://localhost:3309/product_service
    username: product_service
    password: product_service
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true 
    path: /product/v3/api-docs
  swagger-ui:
    enabled: true
    path: /product/swagger-ui.html